version: "3.8"

services:

  nextcloud:
    build:
      context: .
      target: tester
    volumes:
      - ./runtime/docker-entrypoint.d:/docker-entrypoint.d
      - ../server/apps:/var/www/html/apps:ro
      - ../server/lib:/var/www/html/lib:ro
    environment:
      - XDEBUG_SESSION=1
