#!/bin/bash

until wait-for-it ${POSTGRES_HOST}:${POSTGRES_PORT:-5432} > /dev/null 2>&1; do
  echo "Waiting for postgres server ${POSTGRES_HOST}:${POSTGRES_PORT:-5432}"
  sleep 1
done
echo "Postgres server '${POSTGRES_HOST}:${POSTGRES_PORT:-5432}' available."


