#!/bin/bash

run_as() {
    if [ "$(id -u)" = 0 ]; then
        su -p www-data -s /bin/sh -c "$1"
    else
        sh -c "$1"
    fi
}

file_env() {
    local var="$1"
    local fileVar="${var}_FILE"
    local def="${2:-}"
    local varValue=$(env | grep -E "^${var}=" | sed -E -e "s/^${var}=//")
    local fileVarValue=$(env | grep -E "^${fileVar}=" | sed -E -e "s/^${fileVar}=//")
    if [ -n "${varValue}" ] && [ -n "${fileVarValue}" ]; then
        echo >&2 "error: both $var and $fileVar are set (but are exclusive)"
        exit 1
    fi
    if [ -n "${varValue}" ]; then
        export "$var"="${varValue}"
    elif [ -n "${fileVarValue}" ]; then
        export "$var"="$(cat "${fileVarValue}")"
    elif [ -n "${def}" ]; then
        export "$var"="$def"
    fi
    unset "$fileVar"
}

LDAP_CONFIG_FILE=/config/ldap.json
if [[ $(run_as "php occ ldap:show-config") == "" ]]; then
    run_as "php occ ldap:create-empty-config"
fi

file_env LDAP_PASSWORD secret
file_env LDAP_HOST ldap

while IFS="=" read -r key value
do
    if [[ $key == "ldapAgentPassword" ]]; then
        value=${LDAP_PASSWORD}
    fi
    if [[ $key == "ldapHost" ]]; then
        value=${LDAP_HOST}
    fi
    run_as "php occ ldap:set-config \"s01\" \"$key\" \"$value\""
done < <(jq -r '.s01 |to_entries|map("\(.key)=\(.value|tostring)")|.[]' $LDAP_CONFIG_FILE)
