#!/bin/bash

# Disable extensions specified in $NEXTCLOUD_EXTENSIONS_DISABLE env var.


run_as() {
    if [ "$(id -u)" = 0 ]; then
        su -p www-data -s /bin/sh -c "$1"
    else
        sh -c "$1"
    fi
}

IFS="," read -r -a extension <<< "$NEXTCLOUD_EXTENSIONS_DISABLE"
for ext in "${extension[@]}"; do
    run_as "php occ app:disable \"$ext\""
done
